version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ "npm", "run", "dev" ]
    volumes:
      - ./:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_USER = root
      - DATABASE_PASSWORD = root
      - DATABASE_TABLE = portfolio
      - DATABASE_HOST = db
      - DATABASE_DIALECT = postgres
      - SESSION_SECRET = passwordSecret
      - PORT = 3000
      - DATABASE_TIMEZONE = -03:00
      - JWT_TOKEN = abracadabra
    depends_on:
      - db
    command: bash -c "/usr/wait-for-it.sh --timeout=0 portfolio:3036 && node index.js"

  db:
    image: postgres:13
    container_name: portfolio
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_NAME = portfolio
      - NEW_POSTGRES_NAME = portfolio
      - POSTGRES_PASSWORD = root
      - POSTGRES_USER = root
      - POSTGRES_DB = portfolio=value
